<?php
$this->headTitle('Kayak25 - панель администратора');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'E-mail',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>
<section id="login">
    <div class="login-form">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-12" style="float:none;margin:0 auto;">
                    <form class="form-signin" method="post">
                        <h2 class="form-signin-heading">Вход</h2>
                        <?php if ($isLoginError): ?>
                            <div class="alert alert-warning" role="alert">
                                Incorrect login and/or password.
                                <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                            </div>
                        <?php endif; ?>
                        <?= $this->formLabel($form->get('email')); ?>
                        <?= $this->formElement($form->get('email')); ?>
                        <?= $this->formLabel($form->get('password')); ?>
                        <?= $this->formElement($form->get('password')); ?>
                        <div class="checkbox">
                            <label>
                                <?= $this->formElement($form->get('remember_me')); ?> Remember me
                            </label>
                        </div>
                        <?= $this->formElement($form->get('redirect_url')); ?>
                        <?= $this->formElement($form->get('csrf')) ?>

                        <button type="submit" class="btn btn-primary">
                            <i class="fa fa-sign-in"></i> Sign in
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>