<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Kayak25 - Панель администратора')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('fonts/KaushanScript.css'))
        //->prependStylesheet($this->basePath('css/color/blue.css'))
        ->prependStylesheet($this->basePath('css/responsive.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('css/owl.theme.css'))
        ->prependStylesheet($this->basePath('css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/modernizr.custom.js'))

    ?>

    <!--[if lt IE 9]>
    <?= $this->headScript()
    ->prependFile($this->basePath('js/libs/html5shiv.js'))
    ->prependFile($this->basePath('js/libs/respond.min.js'))
    ?>
    <![endif]-->

</head>
<body id="admin-panel">

<?php
$this->adminMenu()->setItems([
    [
        'id' => 'main',
        'label' => 'Home',
        'link' => $this->url('admin')
    ],
    [
        'id' => 'users',
        'label' => 'Users',
        'link' => $this->url('admin', ['action' => 'users'])

    ],
    [
        'id' => 'gallery',
        'label' => 'Gallery',
        'link' => $this->url('admin', ['action' => 'albums'])
    ],
    [
        'id' => 'testimonials',
        'label' => 'Reviews',
        'link' => $this->url('admin', ['action' => 'testimonials'])
    ],
    [
        'id' => 'shop',
        'label' => 'Shop',
        'link' => $this->url('admin', ['action' => 'shop'])
    ],
    [
        'id' => 'orders',
        'label' => 'Orders',
        'link' => $this->url('admin', ['action' => 'orders'])
    ],
    [
        'id' => 'commanders',
        'label' => 'Commanders',
        'link' => $this->url('admin', ['action' => 'commanders'])

    ],
    [
        'id' => 'counters',
        'label' => 'Counters',
        'link' => $this->url('admin', ['action' => 'counters'])
    ],

    [
        'id' => 'partners',
        'label' => 'Partners',
        'link' => $this->url('admin', ['action' => 'partners'])
    ]
]);

echo $this->adminMenu()->render();
?>


<section id='admin-panel-content'>
    <?= $this->pageBreadcrumbs()->render(); ?>
    <?= $this->content ?>

</section>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/admin.js'))
    ->prependFile($this->basePath('js/icon-handler.js'))
    ->prependFile($this->basePath('js/script.js'))
    ->prependFile($this->basePath('js/jqBootstrapValidation.js'))
    ->prependFile($this->basePath('js/styleswitcher.js'))
    ->prependFile($this->basePath('js/jquery.fitvids.js'))
    ->prependFile($this->basePath('js/owl.carousel.min.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
    ->prependFile($this->basePath('js/jquery.appear.js'))
    ->prependFile($this->basePath('js/count-to.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-2.1.1.min.js'))
?>
</body>
</html>
