<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Kayak25 - Активный отдых на каяках')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
</head>
<body>
<h1>Sorry, site is under maintenance now. See you later.</h1>
<h1>Извините, сайт на техобслуживании. Заходите позже.</h1>
</body>
</html>
