<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Kayak25 - Активный отдых на каяках')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <script src='https://www.google.com/recaptcha/api.js' defer></script>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('fonts/KaushanScript.css'))
        ->prependStylesheet($this->basePath('css/color/blue.css'))
        ->prependStylesheet($this->basePath('css/responsive.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('css/owl.theme.css'))
        ->prependStylesheet($this->basePath('css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('asset/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/modernizr.custom.js'))
    ?>
    <style>
        .grecaptcha-badge {
            display: none;
        }
    </style>

    <!--[if lt IE 9]>
    <?= $this->headScript()
    ->prependFile($this->basePath('js/libs/html5shiv.js'))
    ->prependFile($this->basePath('js/libs/respond.min.js'))
    ?>
    <![endif]-->


</head>
<body>

<?= $this->content ?>
<div id="loader">
    <div class="spinner">
        <div class="dot1"></div>
        <div class="dot2"></div>
    </div>
</div>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/basket.js'))
    ->prependFile($this->basePath('js/script.js'))
    ->prependFile($this->basePath('js/jqBootstrapValidation.js'))
    ->prependFile($this->basePath('js/styleswitcher.js'))
    ->prependFile($this->basePath('js/jquery.fitvids.js'))
    ->prependFile($this->basePath('js/owl.carousel.min.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
    ->prependFile($this->basePath('js/jquery.appear.js'))
    ->prependFile($this->basePath('js/count-to.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
    ->prependFile($this->basePath('asset/js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-2.1.1.min.js')) ?>
<script type="text/javascript">
    jQuery(function ($) {
        $("#user-phone").mask("+7 (999) 999-9999");
    });
</script>
<script src="/js/order.js" async defer></script>
<script>
</script>
</body>
</html>
