<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Kayak25 - Панель администратора')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('fonts/KaushanScript.css'))
        ->prependStylesheet($this->basePath('css/responsive.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/owl.transitions.css'))
        ->prependStylesheet($this->basePath('css/owl.theme.css'))
        ->prependStylesheet($this->basePath('css/owl.carousel.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/modernizr.custom.js'))
    ?>

    <!--[if lt IE 9]>
    <?= $this->headScript()
    ->prependFile($this->basePath('js/libs/html5shiv.js'))
    ->prependFile($this->basePath('js/libs/respond.min.js'))
    ?>
    <![endif]-->

</head>
<body>
<?= $this->content ?>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/script.js'))
    ->prependFile($this->basePath('js/contact_me.js'))
    ->prependFile($this->basePath('js/jqBootstrapValidation.js'))
    ->prependFile($this->basePath('js/jquery.fitvids.js'))
    ->prependFile($this->basePath('js/owl.carousel.min.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
    ->prependFile($this->basePath('js/jquery.appear.js'))
    ->prependFile($this->basePath('js/count-to.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-2.1.1.min.js')) ?>
</body>
</html>
