<?php
$this->headTitle('Add Partner');

$form->get('name')->setAttributes([
    'class' => 'form-control'
]);

$form->get('img')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();

$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
    'Partners' => $this->url('admin', ['action' => 'partners']),
    'Add new partner' => $this->url('admin', ['action' => 'add-partner'])
]);
?>

<div class="container">
    <div class="row">

        <div class="col-md-4 text-center" style="float: none;margin: 0 auto;">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('img')); ?>
                <?= $this->formElement($form->get('img')); ?>
                <?= $this->formElementErrors($form->get('img')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

