<?php
$this->headTitle('Add Shop Item');

$form->get('name')->setAttributes([
    'class' => 'form-control'
]);

$form->get('description')->setAttributes([
    'class' => 'form-control'
]);
$form->get('cost')->setAttributes([
    'class' => 'form-control'
]);

$form->get('image')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();

$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
    'Shop' => $this->url('admin', ['action' => 'shop']),
    'Add new item' => $this->url('admin', ['action' => 'add-shop-item'])
]);
?>

<div class="container">
    <div class="row">

        <div class="col-md-6 text-center" style="float: none;margin: 0 auto;">
            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('name')); ?>
                <?= $this->formElement($form->get('name')); ?>
                <?= $this->formElementErrors($form->get('name')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('cost')); ?>
                <?= $this->formElement($form->get('cost')); ?>
                <?= $this->formElementErrors($form->get('cost')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('description')); ?>
                <?= $this->formElement($form->get('description')); ?>
                <?= $this->formElementErrors($form->get('description')); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($form->get('image')); ?>
                <?= $this->formElement($form->get('image')); ?>
                <?= $this->formElementErrors($form->get('image')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

