<?php
$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
]);
$this->adminMenu()->setActiveItemId('main');
?>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Welcome message</h3>
            <p>Welcome to administration panel!</p>
            <?php if ($flag->getValue()): ?>
                <input id="mt-flag" type="checkbox" checked><label for="mt-flag">Maintenance</label>
            <?php else: ?>
                <input id="mt-flag" type="checkbox"><label for="mt-flag">Maintenance</label>
            <?php endif; ?>
        </div>
    </div>

</div>
