<?php
$this->headTitle('Gallery');


$this->adminMenu()->setActiveItemId('gallery');

$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
    'Gallery' => $this->url('admin', ['action' => 'albums'])
]);
$this->flashMessenger()->render('error', ['alert', 'alert-warning']);
$this->flashMessenger()->render('success', ['alert', 'alert-success']);
$this->flashMessenger()->render('info', ['alert', 'alert-info']);
?>
<div class="container">
    <div class="row">

        <div class="col-md-12 text-center" style="padding-bottom: 20px">
            <a class="btn btn-default" href="
    <?= $this->url('admin', ['action' => 'add-album']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add album
            </a>
        </div>
        <div class="col-md-12">
            <table class="table table-striped">

                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Actions</th>
                </tr>

                <?php foreach ($albums as $album): ?>

                    <tr data-href="<?= $this->url('admin', ['action' => 'view-album', 'id' => $album->getId()]); ?>">
                        <td><?= $this->escapeHtml($album->getId()); ?></td>
                        <td><?= $this->escapeHtml($album->getDate()); ?>
                        </td>
                        <td>
                            <?= $this->escapeHtml($album->getName()); ?>
                        </td>
                        <td><?= $this->escapeHtml($album->getDescription()); ?>
                        </td>
                        <td>
                            <a class="btn btn-info" href="<?= $this->url('admin',
                                ['action' => 'edit-album', 'id' => $album->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </a>
                            <a class="btn btn-default btn-danger" href="<?= $this->url('admin',
                                ['action' => 'delete-album', 'id' => $album->getId()]); ?>">
                                <span class="glyphicon glyphicon-remove-circle"></span> Delete
                            </a>
                        </td>
                    </tr>

                <?php endforeach; ?>

            </table>
        </div>
        <div class="col-md-12 text-center">
            <?= $this->paginationControl($albums,
                'Sliding',
                'application/partial/paginator',
                array('route' => 'admin', ['action' => 'albums'])); ?>
        </div>
    </div>
</div>
