<?php
$this->headTitle('Reviews');


$this->adminMenu()->setActiveItemId('testimonials');

$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
    'Reviews' => $this->url('admin', ['action' => 'testimonials'])
]);

$this->flashMessenger()->render('error', ['alert', 'alert-warning']);
$this->flashMessenger()->render('success', ['alert', 'alert-success']);
$this->flashMessenger()->render('info', ['alert', 'alert-info']);
?>
<div class="container">
    <div class="row">

        <div class="col-md-12 text-center" style="padding-bottom: 20px">
            <a class="btn btn-default" href="
    <?= $this->url('admin', ['action' => 'add-testimonial']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add review
            </a>
        </div>
        <div class="col-md-12">
            <table class="table table-striped">

                <tr>
                    <th>ID</th>
                    <th>Author</th>
                    <th>Description</th>
                    <th>Text</th>
                    <th>Actions</th>
                </tr>

                <?php foreach ($testimonials as $testimonial): ?>

                    <tr>
                        <td><?= $this->escapeHtml($testimonial->getId()); ?></td>
                        <td class="col-sm-1">
                            <a href="<?= $this->url('admin', ['action' => 'view-testimonial', 'id' => $testimonial->getId()]); ?>">
                                <?= $this->escapeHtml($testimonial->getAuthor()); ?>
                            </a>
                        </td>
                        <td class="col-sm-1"><?= $this->escapeHtml($testimonial->getDescription()); ?>
                        </td>
                        <td class="col-sm-8"><?= $this->escapeHtml($testimonial->getText()); ?></td>
                        <td class="col-sm-2">
                            <a class="btn btn-info" href="<?= $this->url('admin',
                                ['action' => 'edit-testimonial', 'id' => $testimonial->getId()]); ?>">
                                <span class="glyphicon glyphicon-pencil"></span> Edit
                            </a>
                            <a class="btn btn-default btn-danger" href="<?= $this->url('admin',
                                ['action' => 'delete-testimonial', 'id' => $testimonial->getId()]); ?>">
                                <span class="glyphicon glyphicon-remove-circle"></span> Delete
                            </a>
                        </td>
                    </tr>

                <?php endforeach; ?>

            </table>
        </div>
        <div class="col-md-12 text-center">
            <?= $this->paginationControl($testimonials,
                'Sliding',
                'application/partial/paginator',
                array('route' => 'admin', ['action' => 'testimonials'])); ?>
        </div>
    </div>
</div>
