<?php
$this->headTitle('View ' . $testimonial->getAuthor() . '\'s review');


$this->pageBreadcrumbs()->setItems([
    'Main' => $this->url('admin'),
    'Reviews' => $this->url('admin', ['action' => 'testimonials']),
    'View ' . $testimonial->getAuthor() . '\'s review' => $this->url('admin', ['action' => 'view-testimonial'])
]);
?>


<div class="container text-center">
    <div class="row">
        <div class="col-md-6 text-center" style="float: none;margin: 0 auto;">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td><?= $this->escapeHtml($testimonial->getId()) ?></td>
                    <td rowspan="3"><img src="<?= $this->escapeHtml($testimonial->getPhoto()) ?>"
                                         style="width: 150px;height: auto;"/></td>
                </tr>
                <tr>
                    <th>Author:</th>
                    <td><?= $this->escapeHtml($testimonial->getAuthor()) ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($testimonial->getDescription()) ?></td>
                </tr>
                <tr>
                    <th>Review:</th>
                    <td colspan="3"><?= $this->escapeHtml($testimonial->getText()) ?></td>
                </tr>

            </table>

            <span>
            <a class="btn btn-info" href="<?= $this->url('admin',
                ['action' => 'edit-testimonial', 'id' => $testimonial->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil"></span> Edit
            </a>
            <a class="btn btn-default btn-danger" href="<?= $this->url('admin',
                ['action' => 'delete-testimonial', 'id' => $testimonial->getId()]); ?>">
                <span class="glyphicon glyphicon-remove-circle"></span> Delete
            </a>
        </span>
        </div>
    </div>
</div>