<?php
$this->headTitle('View User');

?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<div class="container text-center">
    <div class="row">
        <div class="col-md-6 text-center" style="float: none;margin: 0 auto;">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>ID:</th>
                    <td>
                    <?= $this->escapeHtml($user->getId()) ?></th>
                </tr>
                <tr>
                    <th>E-mail:</th>
                    <td>
                    <?= $this->escapeHtml($user->getEmail()) ?></th>
                </tr>
                <tr>
                    <th>Full Name:</th>
                    <td>
                    <?= $this->escapeHtml($user->getFullName()) ?></th>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td>
                    <?= $this->escapeHtml($user->getDateCreated()) ?></th>
                </tr>
                <tr>
                    <th>Status:</th>
                    <td>
                    <?= $this->escapeHtml($user->getStatusAsString()) ?></th>
                </tr>

            </table>

            <span>
            <a class="btn btn-info" href="<?= $this->url('admin',
                ['action' => 'editUser', 'id' => $user->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil"></span> Edit
            </a>
            <a class="btn btn-default" href="<?= $this->url('admin',
                ['action' => 'change-password', 'id' => $user->getId()]); ?>">
                <span class="glyphicon glyphicon-asterisk"></span> Change Password
            </a>
        </span>
        </div>
    </div>
</div>