<section id="about-us" class="about-us-section-1">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="section-title text-center">
                    <h3>Три принципа нашей работы</h3>
                    <p></p>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-md-4">
                <div class="welcome-section text-center">
                    <img src="img/about-01.jpg" class="img-responsive" alt="..">
                    <h4>Укрепляем тело и дух</h4>
                    <div class="border"></div>
                    <p>Каякинг отлично влияет на физическое и психическое здоровье.</p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="welcome-section text-center">
                    <img src="img/about-02.jpg" class="img-responsive" alt="..">
                    <h4>Риск должен быть разумным</h4>
                    <div class="border"></div>
                    <p>В наших руках вы можете быть уверены в своей безопасности.</p>
                </div>
            </div>

            <div class="col-md-4">
                <div class="welcome-section text-center">
                    <img src="img/about-03.jpg" class="img-responsive" alt="..">
                    <h4>Мы — банда</h4>
                    <div class="border"></div>
                    <p>Всегда приятно встретить единомышленников на просторах океана.</p>
                </div>
            </div>

        </div><!-- /.row -->

    </div><!-- /.container -->
</section>