<section id="team" class="team-member-section">
    <div class="container" style="text-align: center;">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="section-title text-center">
                    <h3>Наши люди</h3>
                    <p>Покорители морских просторов</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div id="team-section">
                    <div class="our-team">
                        <?php
                        foreach ($this->commanders as $commander) {
                            echo $this->partial('application/index/commander', ['commander' => $commander]);
                        }
                        ?>
                    </div>


                </div>
            </div>
        </div>

    </div>
</section>