<footer class="style-1">
    <div class="container">
        <div class="row">
            <!--<div class="col-md-4 col-xs-12">
                <div class="footer-social text-center">
                    <ul>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    </ul>
                </div>
            </div>-->
            <div class="col-md-4 col-xs-12">
                <div class="footer-link">
                    <ul class="pull-right white-text">
                        <li><?= date('Y') ?> Kayak25. All rights reserved.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>