<section id="page-top">
    <!-- Carousel -->
    <div id="main-slide" class="carousel slide" data-ride="carousel">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#main-slide" data-slide-to="0" class="active"></li>
            <li data-target="#main-slide" data-slide-to="1"></li>
            <li data-target="#main-slide" data-slide-to="2"></li>
        </ol>
        <!--/ Indicators end-->

        <!-- Carousel inner -->
        <div class="carousel-inner">
            <div class="item active">
                <img class="img-responsive" src="img/header-bg-1.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h1 class="animated3">
                            <span>Активный отдых на <strong>каяках</strong></span>
                        </h1>
                        <p class="animated2">Один поход - впечатления на всю жизнь</p>
                        <br/><br/><br/><br/><br/><br/>
                        <a href="#about-us" class="page-scroll btn btn-primary animated1">Узнать больше</a>
                    </div>

                </div>

            </div>
            <!--/ Carousel item end -->

            <div class="item">
                <img class="img-responsive" src="img/header-bg-2.jpg" alt="slider">

                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h1 class="animated1">
                            <span>Продажа <strong>каяков</strong></span>
                        </h1>
                        <p class="animated2">Продажа каяков и сопутствующего снаряжения по доступным ценам</p>
                        <br/><br/><br/><br/><br/><br/>
                        <a href="#pricing" class="page-scroll btn btn-primary animated3">Ознакомиться</a>
                    </div>
                </div>
            </div>
            <!--/ Carousel item end -->

            <div class="item">
                <img class="img-responsive" src="img/header-bg-3.jpg" alt="slider">
                <div class="slider-content">
                    <div class="col-md-12 text-center">
                        <h1 class="animated2">
                            <span>Оторвись на всю <strong>катушку</strong></span>
                        </h1>
                        <p class="animated1">Аренда каяков и снаряжения</p>
                        <br/><br/><br/><br/><br/><br/>
                        <a class="animated3 page-scroll btn btn-primary" href="#rent">Узнать больше</a>
                    </div>
                </div>
            </div>
            <!--/ Carousel item end -->
        </div>
        <!-- Carousel inner end-->

        <!-- Controls -->
        <a class="left carousel-control" href="#main-slide" data-slide="prev">
            <span><i class="fa fa-angle-left"></i></span>
        </a>
        <a class="right carousel-control" href="#main-slide" data-slide="next">
            <span><i class="fa fa-angle-right"></i></span>
        </a>
    </div>
    <!-- /carousel -->
</section>