<?= $this->partial('application/index/navbar'); ?>
<?= $this->partial('application/index/shop-cart-modal'); ?>
<a href="#view-cart" data-toggle="modal">
    <div id="basket">
        <span class="notification-counter">0</span>
        <i class="fa fa-shopping-cart"></i>
    </div>
</a>
<?= $this->partial('application/index/head_slider'); ?>
<?= $this->partial('application/index/about_us'); ?>
<?= $this->partial('application/index/albumlist.phtml'); ?>
<?= $this->partial('application/index/commandersection'); ?>
<?= $this->partial('application/index/testimonialsection'); ?>
<?= $this->partial('application/index/shop-section'); ?>
<?= $this->partial('application/index/contacts'); ?>




